version: "3.9"

volumes:
  postgres:
  pgadmin:
  redis:
  rediscommander:

services:
  postgres:
    container_name: demo_postgres
    image: "postgres:13"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: "/data/postgres"
    volumes:
      - postgres:/data/postgres
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    container_name: demo_pgadmin
    image: "dpage/pgadmin4:5"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./docker_pgadmin_servers.json:/pgadmin4/servers.json
    ports:
      - "8000:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:postgres' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped

  redis:
    container_name: demo_redis
    image: "redis:6"
    ports:
      - "6379:6379"
    restart: unless-stopped

  rediscommander:
    container_name: demo_rediscommander
    image: "rediscommander/redis-commander"
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8001:8081"
    restart: unless-stopped
